"""build_skills_db.py -- deterministic generator for data/skills.json.

The output JSON is the source of truth loaded by engine/skills_db.py at
runtime; this file is the source of truth for the JSON. Regenerate with:

    python tools/build_skills_db.py

Category dicts keep the DB reviewable in diffs; add a canonical + its
aliases in the right category, rerun, commit both files. Aliases must be
lowercase, space-normalized. Canonical form is whatever the industry
actually writes (mixed case OK -- matching is case-insensitive).

Design contract (tested in tests/test_skills_db.py):
- >=500 canonical skills, >=500 canonical titles
- Well-known skills present (Python/JavaScript/Docker/Kubernetes/React/AWS/Git)
- Hardware skills present (FPGA/Verilog/Vivado/signal integrity/PCB/Altium)
- Well-known titles present (software/data/devops/hardware engineer)
"""
from __future__ import annotations
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT_PATH = os.path.join(ROOT, "data", "skills.json")


# ---------- SKILLS -----------------------------------------------------------
SKILLS: dict[str, list[dict]] = {
    "language": [
        {"canonical": "Python", "aliases": ["python3", "py3"]},
        {"canonical": "Java", "aliases": []},
        {"canonical": "JavaScript", "aliases": ["js", "ecmascript"]},
        {"canonical": "TypeScript", "aliases": ["ts"]},
        {"canonical": "C", "aliases": []},
        {"canonical": "C++", "aliases": ["cpp", "c plus plus", "c/c++"]},
        {"canonical": "C#", "aliases": ["csharp", "c sharp"]},
        {"canonical": "Go", "aliases": ["golang"]},
        {"canonical": "Rust", "aliases": []},
        {"canonical": "Ruby", "aliases": []},
        {"canonical": "Swift", "aliases": []},
        {"canonical": "Kotlin", "aliases": []},
        {"canonical": "Scala", "aliases": []},
        {"canonical": "Perl", "aliases": []},
        {"canonical": "PHP", "aliases": []},
        {"canonical": "R", "aliases": []},
        {"canonical": "MATLAB", "aliases": ["matlab/simulink"]},
        {"canonical": "Julia", "aliases": []},
        {"canonical": "Dart", "aliases": []},
        {"canonical": "Lua", "aliases": []},
        {"canonical": "Elixir", "aliases": []},
        {"canonical": "Erlang", "aliases": []},
        {"canonical": "Haskell", "aliases": []},
        {"canonical": "F#", "aliases": ["fsharp"]},
        {"canonical": "Clojure", "aliases": []},
        {"canonical": "Groovy", "aliases": []},
        {"canonical": "Assembly", "aliases": ["asm", "assembler"]},
        {"canonical": "Objective-C", "aliases": ["obj-c", "objectivec"]},
        {"canonical": "VB.NET", "aliases": ["visual basic", "vb dot net"]},
        {"canonical": "COBOL", "aliases": []},
        {"canonical": "Fortran", "aliases": []},
        {"canonical": "Bash", "aliases": ["bash scripting"]},
        {"canonical": "PowerShell", "aliases": ["powershell scripting"]},
        {"canonical": "Shell", "aliases": ["shell scripting", "sh"]},
        {"canonical": "Zsh", "aliases": []},
        {"canonical": "Tcl", "aliases": ["tcl/tk"]},
        {"canonical": "Racket", "aliases": []},
        {"canonical": "Scheme", "aliases": []},
        {"canonical": "Lisp", "aliases": ["common lisp"]},
        {"canonical": "OCaml", "aliases": []},
        {"canonical": "Ada", "aliases": []},
        {"canonical": "Pascal", "aliases": []},
        {"canonical": "Delphi", "aliases": []},
        {"canonical": "Solidity", "aliases": []},
        {"canonical": "Vyper", "aliases": []},
        {"canonical": "Nim", "aliases": []},
        {"canonical": "Crystal", "aliases": []},
        {"canonical": "Zig", "aliases": []},
        {"canonical": "Prolog", "aliases": []},
        {"canonical": "Smalltalk", "aliases": []},
        {"canonical": "ActionScript", "aliases": []},
        {"canonical": "ABAP", "aliases": []},
        {"canonical": "Apex", "aliases": ["salesforce apex"]},
        {"canonical": "CoffeeScript", "aliases": []},
        {"canonical": "PureScript", "aliases": []},
        {"canonical": "ReasonML", "aliases": ["reason"]},
        {"canonical": "Elm", "aliases": []},
        {"canonical": "Odin", "aliases": []},
        {"canonical": "V", "aliases": ["vlang"]},
        {"canonical": "Vala", "aliases": []},
        {"canonical": "Nix", "aliases": []},
    ],
    "web_frontend": [
        {"canonical": "React", "aliases": ["reactjs", "react.js"]},
        {"canonical": "Angular", "aliases": ["angularjs", "angular2"]},
        {"canonical": "Vue.js", "aliases": ["vue", "vuejs"]},
        {"canonical": "Svelte", "aliases": ["sveltekit"]},
        {"canonical": "Next.js", "aliases": ["nextjs", "next js"]},
        {"canonical": "Nuxt.js", "aliases": ["nuxt", "nuxtjs"]},
        {"canonical": "Gatsby", "aliases": ["gatsbyjs"]},
        {"canonical": "Remix", "aliases": []},
        {"canonical": "Ember.js", "aliases": ["ember", "emberjs"]},
        {"canonical": "Backbone.js", "aliases": ["backbone", "backbonejs"]},
        {"canonical": "jQuery", "aliases": []},
        {"canonical": "Alpine.js", "aliases": ["alpinejs"]},
        {"canonical": "Solid.js", "aliases": ["solidjs"]},
        {"canonical": "Preact", "aliases": []},
        {"canonical": "Lit", "aliases": ["litelement", "lit-html"]},
        {"canonical": "Stimulus", "aliases": ["stimulusjs"]},
        {"canonical": "HTMX", "aliases": []},
        {"canonical": "HTML", "aliases": ["html5"]},
        {"canonical": "CSS", "aliases": ["css3"]},
        {"canonical": "SASS", "aliases": ["scss"]},
        {"canonical": "LESS", "aliases": []},
        {"canonical": "Stylus", "aliases": []},
        {"canonical": "Tailwind CSS", "aliases": ["tailwind", "tailwindcss"]},
        {"canonical": "Bootstrap", "aliases": []},
        {"canonical": "Material UI", "aliases": ["mui", "material-ui"]},
        {"canonical": "Chakra UI", "aliases": []},
        {"canonical": "Ant Design", "aliases": ["antd"]},
        {"canonical": "Bulma", "aliases": []},
        {"canonical": "Foundation", "aliases": []},
        {"canonical": "Semantic UI", "aliases": []},
        {"canonical": "Storybook", "aliases": []},
        {"canonical": "Webpack", "aliases": []},
        {"canonical": "Vite", "aliases": []},
        {"canonical": "Rollup", "aliases": ["rollup.js"]},
        {"canonical": "Parcel", "aliases": []},
        {"canonical": "Babel", "aliases": ["babeljs"]},
        {"canonical": "ESLint", "aliases": []},
        {"canonical": "Prettier", "aliases": []},
        {"canonical": "PostCSS", "aliases": []},
        {"canonical": "Turbopack", "aliases": []},
        {"canonical": "esbuild", "aliases": []},
        {"canonical": "PWA", "aliases": ["progressive web app"]},
        {"canonical": "Web Components", "aliases": []},
    ],
    "web_backend": [
        {"canonical": "Django", "aliases": []},
        {"canonical": "Flask", "aliases": []},
        {"canonical": "FastAPI", "aliases": []},
        {"canonical": "Tornado", "aliases": []},
        {"canonical": "Pyramid", "aliases": []},
        {"canonical": "Bottle", "aliases": []},
        {"canonical": "Rails", "aliases": ["ruby on rails", "rubyonrails"]},
        {"canonical": "Sinatra", "aliases": []},
        {"canonical": "Spring", "aliases": []},
        {"canonical": "Spring Boot", "aliases": ["springboot"]},
        {"canonical": "Express", "aliases": ["expressjs", "express.js"]},
        {"canonical": "Koa", "aliases": ["koajs"]},
        {"canonical": "NestJS", "aliases": ["nest.js"]},
        {"canonical": "Fastify", "aliases": []},
        {"canonical": "Hapi", "aliases": ["hapijs"]},
        {"canonical": "Meteor", "aliases": ["meteorjs"]},
        {"canonical": "Sails", "aliases": ["sailsjs"]},
        {"canonical": "LoopBack", "aliases": ["loopback.js"]},
        {"canonical": "Strapi", "aliases": []},
        {"canonical": "Adonis", "aliases": ["adonisjs"]},
        {"canonical": "Laravel", "aliases": []},
        {"canonical": "Symfony", "aliases": []},
        {"canonical": "CakePHP", "aliases": ["cake php"]},
        {"canonical": "CodeIgniter", "aliases": []},
        {"canonical": "Yii", "aliases": []},
        {"canonical": "Zend", "aliases": ["zend framework"]},
        {"canonical": "ASP.NET", "aliases": ["asp dot net", "aspnet"]},
        {"canonical": "ASP.NET Core", "aliases": ["asp.net core", "aspnet core"]},
        {"canonical": ".NET", "aliases": ["dotnet", "dot net", ".net core"]},
        {"canonical": "Blazor", "aliases": []},
        {"canonical": "Play Framework", "aliases": ["playframework"]},
        {"canonical": "Phoenix", "aliases": ["phoenix framework"]},
        {"canonical": "Gin", "aliases": ["gin gonic"]},
        {"canonical": "Echo", "aliases": ["echo framework"]},
        {"canonical": "Fiber", "aliases": []},
        {"canonical": "Actix", "aliases": ["actix-web"]},
        {"canonical": "Rocket", "aliases": ["rocket.rs"]},
        {"canonical": "Warp", "aliases": []},
        {"canonical": "Axum", "aliases": []},
        {"canonical": "Micronaut", "aliases": []},
        {"canonical": "Quarkus", "aliases": []},
        {"canonical": "Ktor", "aliases": []},
        {"canonical": "Vert.x", "aliases": ["vertx"]},
        {"canonical": "Grails", "aliases": []},
    ],
    "database": [
        {"canonical": "PostgreSQL", "aliases": ["postgres", "psql"]},
        {"canonical": "MySQL", "aliases": []},
        {"canonical": "MariaDB", "aliases": []},
        {"canonical": "SQLite", "aliases": []},
        {"canonical": "MongoDB", "aliases": ["mongo"]},
        {"canonical": "Redis", "aliases": []},
        {"canonical": "Memcached", "aliases": []},
        {"canonical": "Cassandra", "aliases": ["apache cassandra"]},
        {"canonical": "DynamoDB", "aliases": ["dynamo"]},
        {"canonical": "Cosmos DB", "aliases": ["cosmosdb"]},
        {"canonical": "Bigtable", "aliases": ["cloud bigtable"]},
        {"canonical": "HBase", "aliases": ["apache hbase"]},
        {"canonical": "Neo4j", "aliases": []},
        {"canonical": "ArangoDB", "aliases": []},
        {"canonical": "OrientDB", "aliases": []},
        {"canonical": "InfluxDB", "aliases": ["influx"]},
        {"canonical": "TimescaleDB", "aliases": ["timescale"]},
        {"canonical": "Elasticsearch", "aliases": ["elastic search", "es"]},
        {"canonical": "OpenSearch", "aliases": []},
        {"canonical": "Solr", "aliases": ["apache solr"]},
        {"canonical": "Meilisearch", "aliases": []},
        {"canonical": "Typesense", "aliases": []},
        {"canonical": "Snowflake", "aliases": []},
        {"canonical": "BigQuery", "aliases": ["google bigquery"]},
        {"canonical": "Redshift", "aliases": ["amazon redshift"]},
        {"canonical": "Databricks", "aliases": []},
        {"canonical": "Presto", "aliases": []},
        {"canonical": "Trino", "aliases": []},
        {"canonical": "Hive", "aliases": ["apache hive"]},
        {"canonical": "Impala", "aliases": ["apache impala"]},
        {"canonical": "Firebase", "aliases": []},
        {"canonical": "Firestore", "aliases": ["cloud firestore"]},
        {"canonical": "Realm", "aliases": []},
        {"canonical": "Couchbase", "aliases": []},
        {"canonical": "CouchDB", "aliases": ["apache couchdb"]},
        {"canonical": "RethinkDB", "aliases": []},
        {"canonical": "RavenDB", "aliases": []},
        {"canonical": "MarkLogic", "aliases": []},
        {"canonical": "ClickHouse", "aliases": []},
        {"canonical": "DuckDB", "aliases": []},
        {"canonical": "PlanetScale", "aliases": []},
        {"canonical": "Supabase", "aliases": []},
        {"canonical": "Spanner", "aliases": ["cloud spanner"]},
        {"canonical": "Aurora", "aliases": ["aurora db", "amazon aurora"]},
        {"canonical": "Oracle DB", "aliases": ["oracle database", "oracledb"]},
        {"canonical": "SQL Server", "aliases": ["mssql", "microsoft sql server", "ms sql"]},
        {"canonical": "DB2", "aliases": ["ibm db2"]},
        {"canonical": "Teradata", "aliases": []},
        {"canonical": "SQL", "aliases": []},
        {"canonical": "T-SQL", "aliases": ["tsql", "transact-sql"]},
        {"canonical": "PL/SQL", "aliases": ["plsql"]},
        {"canonical": "NoSQL", "aliases": ["no sql"]},
        {"canonical": "NewSQL", "aliases": []},
        {"canonical": "GraphDB", "aliases": ["graph database"]},
    ],
    "cloud_devops": [
        {"canonical": "AWS", "aliases": ["amazon web services"]},
        {"canonical": "Azure", "aliases": ["microsoft azure"]},
        {"canonical": "GCP", "aliases": ["google cloud", "google cloud platform"]},
        {"canonical": "DigitalOcean", "aliases": ["digital ocean"]},
        {"canonical": "Linode", "aliases": []},
        {"canonical": "Vultr", "aliases": []},
        {"canonical": "Heroku", "aliases": []},
        {"canonical": "Vercel", "aliases": []},
        {"canonical": "Netlify", "aliases": []},
        {"canonical": "Cloudflare", "aliases": ["cloudflare workers"]},
        {"canonical": "Fly.io", "aliases": ["flyio"]},
        {"canonical": "Render", "aliases": []},
        {"canonical": "Railway", "aliases": []},
        {"canonical": "Docker", "aliases": ["docker containers"]},
        {"canonical": "Kubernetes", "aliases": ["k8s"]},
        {"canonical": "Helm", "aliases": ["helm charts"]},
        {"canonical": "Istio", "aliases": []},
        {"canonical": "Linkerd", "aliases": []},
        {"canonical": "Consul", "aliases": ["hashicorp consul"]},
        {"canonical": "Nomad", "aliases": ["hashicorp nomad"]},
        {"canonical": "Vagrant", "aliases": []},
        {"canonical": "Packer", "aliases": ["hashicorp packer"]},
        {"canonical": "Terraform", "aliases": []},
        {"canonical": "CloudFormation", "aliases": ["aws cloudformation"]},
        {"canonical": "Pulumi", "aliases": []},
        {"canonical": "CDK", "aliases": ["aws cdk", "cloud development kit"]},
        {"canonical": "Ansible", "aliases": []},
        {"canonical": "Chef", "aliases": []},
        {"canonical": "Puppet", "aliases": []},
        {"canonical": "SaltStack", "aliases": ["salt"]},
        {"canonical": "Jenkins", "aliases": []},
        {"canonical": "GitHub Actions", "aliases": ["gh actions"]},
        {"canonical": "GitLab CI", "aliases": ["gitlab ci/cd", "gitlab pipelines"]},
        {"canonical": "CircleCI", "aliases": ["circle ci"]},
        {"canonical": "Travis CI", "aliases": ["travis"]},
        {"canonical": "Bamboo", "aliases": ["atlassian bamboo"]},
        {"canonical": "TeamCity", "aliases": []},
        {"canonical": "Argo CD", "aliases": ["argocd"]},
        {"canonical": "Flux CD", "aliases": ["fluxcd"]},
        {"canonical": "Spinnaker", "aliases": []},
        {"canonical": "Tekton", "aliases": []},
        {"canonical": "Prometheus", "aliases": []},
        {"canonical": "Grafana", "aliases": []},
        {"canonical": "Datadog", "aliases": []},
        {"canonical": "New Relic", "aliases": ["newrelic"]},
        {"canonical": "Splunk", "aliases": []},
        {"canonical": "ELK", "aliases": ["elk stack"]},
        {"canonical": "Logstash", "aliases": []},
        {"canonical": "Kibana", "aliases": []},
        {"canonical": "Fluentd", "aliases": []},
        {"canonical": "Sentry", "aliases": []},
        {"canonical": "PagerDuty", "aliases": ["pager duty"]},
        {"canonical": "OpsGenie", "aliases": []},
        {"canonical": "Nagios", "aliases": []},
        {"canonical": "Zabbix", "aliases": []},
        {"canonical": "Nginx", "aliases": []},
        {"canonical": "Apache HTTP Server", "aliases": ["apache httpd", "apache2"]},
        {"canonical": "HAProxy", "aliases": []},
        {"canonical": "Envoy", "aliases": ["envoy proxy"]},
        {"canonical": "Traefik", "aliases": []},
        {"canonical": "Caddy", "aliases": ["caddy server"]},
        {"canonical": "IIS", "aliases": ["internet information services"]},
        {"canonical": "Tomcat", "aliases": ["apache tomcat"]},
        {"canonical": "Jetty", "aliases": ["eclipse jetty"]},
        {"canonical": "GitOps", "aliases": ["git ops"]},
        {"canonical": "CI/CD", "aliases": ["ci cd", "continuous integration", "continuous delivery"]},
    ],
    "data_ml": [
        {"canonical": "TensorFlow", "aliases": ["tf"]},
        {"canonical": "PyTorch", "aliases": ["torch"]},
        {"canonical": "Keras", "aliases": []},
        {"canonical": "scikit-learn", "aliases": ["sklearn", "scikit learn"]},
        {"canonical": "Pandas", "aliases": []},
        {"canonical": "NumPy", "aliases": ["numpy array"]},
        {"canonical": "SciPy", "aliases": []},
        {"canonical": "XGBoost", "aliases": []},
        {"canonical": "LightGBM", "aliases": ["lgbm"]},
        {"canonical": "CatBoost", "aliases": []},
        {"canonical": "Hugging Face", "aliases": ["huggingface"]},
        {"canonical": "Transformers", "aliases": ["hf transformers"]},
        {"canonical": "LangChain", "aliases": []},
        {"canonical": "LlamaIndex", "aliases": ["llama index"]},
        {"canonical": "spaCy", "aliases": ["spacy nlp"]},
        {"canonical": "NLTK", "aliases": []},
        {"canonical": "Gensim", "aliases": []},
        {"canonical": "OpenCV", "aliases": ["cv2"]},
        {"canonical": "Pillow", "aliases": ["pil"]},
        {"canonical": "MLflow", "aliases": []},
        {"canonical": "Kubeflow", "aliases": []},
        {"canonical": "Ray", "aliases": ["ray serve"]},
        {"canonical": "Dask", "aliases": []},
        {"canonical": "Airflow", "aliases": ["apache airflow"]},
        {"canonical": "Prefect", "aliases": []},
        {"canonical": "Dagster", "aliases": []},
        {"canonical": "Luigi", "aliases": []},
        {"canonical": "dbt", "aliases": ["data build tool"]},
        {"canonical": "Spark", "aliases": ["apache spark", "pyspark"]},
        {"canonical": "Kafka", "aliases": ["apache kafka"]},
        {"canonical": "Flink", "aliases": ["apache flink"]},
        {"canonical": "Storm", "aliases": ["apache storm"]},
        {"canonical": "Samza", "aliases": ["apache samza"]},
        {"canonical": "Beam", "aliases": ["apache beam"]},
        {"canonical": "Hadoop", "aliases": ["apache hadoop"]},
        {"canonical": "MapReduce", "aliases": ["map reduce"]},
        {"canonical": "HDFS", "aliases": []},
        {"canonical": "Iceberg", "aliases": ["apache iceberg"]},
        {"canonical": "Delta Lake", "aliases": ["deltalake"]},
        {"canonical": "Hudi", "aliases": ["apache hudi"]},
        {"canonical": "Tableau", "aliases": []},
        {"canonical": "Power BI", "aliases": ["powerbi"]},
        {"canonical": "Looker", "aliases": []},
        {"canonical": "Superset", "aliases": ["apache superset"]},
        {"canonical": "Metabase", "aliases": []},
        {"canonical": "Qlik", "aliases": ["qlikview", "qlik sense"]},
        {"canonical": "D3.js", "aliases": ["d3js", "d3"]},
        {"canonical": "Plotly", "aliases": []},
        {"canonical": "Bokeh", "aliases": []},
        {"canonical": "Matplotlib", "aliases": []},
        {"canonical": "Seaborn", "aliases": []},
        {"canonical": "Streamlit", "aliases": []},
        {"canonical": "Gradio", "aliases": []},
        {"canonical": "Jupyter", "aliases": ["jupyter notebook", "jupyterlab"]},
        {"canonical": "Weights & Biases", "aliases": ["wandb"]},
        {"canonical": "Vertex AI", "aliases": []},
        {"canonical": "SageMaker", "aliases": ["amazon sagemaker"]},
        {"canonical": "ONNX", "aliases": []},
        {"canonical": "Triton", "aliases": ["triton inference server"]},
        {"canonical": "MLOps", "aliases": ["ml ops"]},
        {"canonical": "Feature Store", "aliases": []},
        {"canonical": "Feast", "aliases": []},
        {"canonical": "RAG", "aliases": ["retrieval augmented generation"]},
        {"canonical": "Vector Database", "aliases": ["vector db"]},
        {"canonical": "Pinecone", "aliases": []},
        {"canonical": "Weaviate", "aliases": []},
        {"canonical": "Milvus", "aliases": []},
        {"canonical": "Chroma", "aliases": ["chromadb"]},
        {"canonical": "Qdrant", "aliases": []},
        {"canonical": "FAISS", "aliases": []},
        {"canonical": "Embeddings", "aliases": ["word embeddings", "sentence embeddings"]},
        {"canonical": "LLM", "aliases": ["large language model"]},
    ],
    "mobile": [
        {"canonical": "iOS", "aliases": ["ios development"]},
        {"canonical": "Android", "aliases": ["android development"]},
        {"canonical": "SwiftUI", "aliases": ["swift ui"]},
        {"canonical": "UIKit", "aliases": []},
        {"canonical": "Flutter", "aliases": []},
        {"canonical": "React Native", "aliases": ["reactnative"]},
        {"canonical": "Xamarin", "aliases": []},
        {"canonical": "Ionic", "aliases": []},
        {"canonical": "Cordova", "aliases": ["apache cordova"]},
        {"canonical": "Capacitor", "aliases": []},
        {"canonical": "Jetpack Compose", "aliases": ["compose ui"]},
        {"canonical": "Room", "aliases": ["android room"]},
        {"canonical": "Core Data", "aliases": ["coredata"]},
        {"canonical": "RxSwift", "aliases": []},
        {"canonical": "RxJava", "aliases": []},
        {"canonical": "Combine", "aliases": ["swift combine"]},
        {"canonical": "Retrofit", "aliases": []},
        {"canonical": "Alamofire", "aliases": []},
        {"canonical": "Fastlane", "aliases": []},
        {"canonical": "TestFlight", "aliases": []},
        {"canonical": "Play Console", "aliases": ["google play console"]},
        {"canonical": "App Store Connect", "aliases": []},
        {"canonical": "ARKit", "aliases": []},
        {"canonical": "ARCore", "aliases": []},
        {"canonical": "Mobile SDK", "aliases": []},
        {"canonical": "MVVM", "aliases": []},
        {"canonical": "MVI", "aliases": []},
        {"canonical": "MVP", "aliases": ["model view presenter"]},
        {"canonical": "Coroutines", "aliases": ["kotlin coroutines"]},
        {"canonical": "Dagger", "aliases": ["dagger2", "hilt"]},
    ],
    "hardware": [
        {"canonical": "FPGA", "aliases": ["field programmable gate array", "fpgas"]},
        {"canonical": "ASIC", "aliases": ["asics"]},
        {"canonical": "PCB", "aliases": ["printed circuit board"]},
        {"canonical": "PCB Layout", "aliases": ["pcb layouts"]},
        {"canonical": "PCB Design", "aliases": []},
        {"canonical": "Schematic Capture", "aliases": ["schematic entry"]},
        {"canonical": "Schematic Design", "aliases": []},
        {"canonical": "Altium", "aliases": ["altium designer"]},
        {"canonical": "KiCad", "aliases": ["kicad eda"]},
        {"canonical": "Eagle", "aliases": ["autodesk eagle"]},
        {"canonical": "OrCAD", "aliases": []},
        {"canonical": "Cadence Allegro", "aliases": ["allegro pcb"]},
        {"canonical": "Mentor Xpedition", "aliases": ["xpedition"]},
        {"canonical": "PADS", "aliases": ["mentor pads"]},
        {"canonical": "Verilog", "aliases": []},
        {"canonical": "SystemVerilog", "aliases": ["system verilog", "sv"]},
        {"canonical": "VHDL", "aliases": []},
        {"canonical": "Chisel", "aliases": []},
        {"canonical": "MyHDL", "aliases": []},
        {"canonical": "Vivado", "aliases": ["xilinx vivado"]},
        {"canonical": "Quartus", "aliases": ["intel quartus", "altera quartus"]},
        {"canonical": "Xilinx", "aliases": []},
        {"canonical": "Intel FPGA", "aliases": ["altera"]},
        {"canonical": "Lattice", "aliases": ["lattice semiconductor"]},
        {"canonical": "Microsemi", "aliases": ["microchip fpga"]},
        {"canonical": "RTL", "aliases": ["register transfer level"]},
        {"canonical": "RTL Design", "aliases": []},
        {"canonical": "ModelSim", "aliases": []},
        {"canonical": "Questa", "aliases": ["questa sim"]},
        {"canonical": "VCS", "aliases": ["synopsys vcs"]},
        {"canonical": "Xcelium", "aliases": []},
        {"canonical": "Synopsys", "aliases": []},
        {"canonical": "Cadence", "aliases": ["cadence design systems"]},
        {"canonical": "Mentor Graphics", "aliases": []},
        {"canonical": "signal integrity", "aliases": ["si analysis"]},
        {"canonical": "power integrity", "aliases": ["pi analysis"]},
        {"canonical": "EMC", "aliases": ["electromagnetic compatibility"]},
        {"canonical": "EMI", "aliases": ["electromagnetic interference"]},
        {"canonical": "ESD", "aliases": ["electrostatic discharge"]},
        {"canonical": "DFM", "aliases": ["design for manufacturing"]},
        {"canonical": "DFT", "aliases": ["design for test"]},
        {"canonical": "DFA", "aliases": ["design for assembly"]},
        {"canonical": "SMT", "aliases": ["surface mount technology"]},
        {"canonical": "Through Hole", "aliases": ["through-hole", "tht"]},
        {"canonical": "BOM", "aliases": ["bill of materials"]},
        {"canonical": "Component Selection", "aliases": []},
        {"canonical": "Impedance Matching", "aliases": []},
        {"canonical": "S-Parameters", "aliases": ["s parameters"]},
        {"canonical": "Antenna Design", "aliases": []},
        {"canonical": "RF", "aliases": ["radio frequency"]},
        {"canonical": "RF Design", "aliases": []},
        {"canonical": "Microwave", "aliases": []},
        {"canonical": "Mixed-Signal", "aliases": ["mixed signal"]},
        {"canonical": "Analog Design", "aliases": []},
        {"canonical": "Digital Design", "aliases": []},
        {"canonical": "Oscilloscope", "aliases": []},
        {"canonical": "Logic Analyzer", "aliases": []},
        {"canonical": "Spectrum Analyzer", "aliases": []},
        {"canonical": "VNA", "aliases": ["vector network analyzer"]},
        {"canonical": "LTSpice", "aliases": ["ltspice iv"]},
        {"canonical": "PSpice", "aliases": ["orcad pspice"]},
        {"canonical": "Simetrix", "aliases": []},
        {"canonical": "HFSS", "aliases": ["ansys hfss"]},
        {"canonical": "ADS", "aliases": ["keysight ads"]},
        {"canonical": "SPICE", "aliases": ["ngspice"]},
        {"canonical": "UVM", "aliases": ["universal verification methodology"]},
        {"canonical": "OVM", "aliases": []},
        {"canonical": "Functional Verification", "aliases": []},
        {"canonical": "Design Verification", "aliases": ["dv"]},
        {"canonical": "Formal Verification", "aliases": []},
        {"canonical": "SoC", "aliases": ["system on chip", "system-on-chip"]},
        {"canonical": "IP Core", "aliases": ["ip cores"]},
        {"canonical": "AXI", "aliases": ["axi4"]},
        {"canonical": "AHB", "aliases": []},
        {"canonical": "APB", "aliases": []},
        {"canonical": "DDR", "aliases": ["ddr3", "ddr4", "ddr5"]},
        {"canonical": "PCIe", "aliases": ["pci express"]},
    ],
    "embedded_firmware": [
        {"canonical": "Embedded C", "aliases": []},
        {"canonical": "Embedded C++", "aliases": []},
        {"canonical": "ARM Cortex", "aliases": []},
        {"canonical": "Cortex-M", "aliases": ["cortex m0", "cortex m3", "cortex m4", "cortex m7"]},
        {"canonical": "Cortex-A", "aliases": []},
        {"canonical": "Cortex-R", "aliases": []},
        {"canonical": "STM32", "aliases": ["stm32f4", "stm32h7"]},
        {"canonical": "NXP", "aliases": ["nxp kinetis", "nxp imx"]},
        {"canonical": "Nordic", "aliases": ["nrf52", "nrf53", "nordic semiconductor"]},
        {"canonical": "ESP32", "aliases": []},
        {"canonical": "ESP8266", "aliases": []},
        {"canonical": "PIC", "aliases": ["microchip pic"]},
        {"canonical": "AVR", "aliases": ["atmega"]},
        {"canonical": "MSP430", "aliases": []},
        {"canonical": "Atmel", "aliases": []},
        {"canonical": "Arduino", "aliases": []},
        {"canonical": "Raspberry Pi", "aliases": ["rpi"]},
        {"canonical": "BeagleBone", "aliases": []},
        {"canonical": "Zephyr", "aliases": ["zephyr rtos"]},
        {"canonical": "FreeRTOS", "aliases": []},
        {"canonical": "ThreadX", "aliases": ["azure rtos"]},
        {"canonical": "VxWorks", "aliases": []},
        {"canonical": "QNX", "aliases": []},
        {"canonical": "RTLinux", "aliases": ["real time linux"]},
        {"canonical": "uC/OS", "aliases": ["ucos", "micrium"]},
        {"canonical": "RTOS", "aliases": ["real time operating system"]},
        {"canonical": "Bare Metal", "aliases": ["baremetal", "bare-metal"]},
        {"canonical": "Bootloader", "aliases": []},
        {"canonical": "U-Boot", "aliases": ["uboot"]},
        {"canonical": "Yocto", "aliases": ["yocto project"]},
        {"canonical": "Buildroot", "aliases": []},
        {"canonical": "Linux Kernel", "aliases": ["kernel development"]},
        {"canonical": "Device Drivers", "aliases": ["kernel drivers", "device driver"]},
        {"canonical": "Kernel Module", "aliases": ["lkm"]},
        {"canonical": "DMA", "aliases": ["direct memory access"]},
        {"canonical": "Interrupts", "aliases": ["isr", "interrupt handler"]},
        {"canonical": "ADC", "aliases": ["analog to digital converter"]},
        {"canonical": "DAC", "aliases": ["digital to analog converter"]},
        {"canonical": "PWM", "aliases": ["pulse width modulation"]},
        {"canonical": "GPIO", "aliases": ["general purpose io"]},
        {"canonical": "I2C", "aliases": ["i²c"]},
        {"canonical": "SPI", "aliases": []},
        {"canonical": "UART", "aliases": ["serial port"]},
        {"canonical": "CAN Bus", "aliases": ["can bus", "canbus"]},
        {"canonical": "LIN", "aliases": ["lin bus"]},
        {"canonical": "MODBUS", "aliases": []},
        {"canonical": "USB", "aliases": ["usb 2.0", "usb 3.0"]},
        {"canonical": "Ethernet", "aliases": []},
        {"canonical": "TCP/IP", "aliases": ["tcp ip"]},
        {"canonical": "MQTT", "aliases": []},
        {"canonical": "CoAP", "aliases": []},
        {"canonical": "BLE", "aliases": ["bluetooth low energy"]},
        {"canonical": "Bluetooth", "aliases": []},
        {"canonical": "Wi-Fi", "aliases": ["wifi", "wireless lan"]},
        {"canonical": "LoRa", "aliases": ["lorawan"]},
        {"canonical": "Zigbee", "aliases": []},
        {"canonical": "Thread", "aliases": ["thread mesh"]},
        {"canonical": "Matter", "aliases": ["matter smart home"]},
        {"canonical": "Bring-Up", "aliases": ["board bring-up", "bringup"]},
        {"canonical": "Low-Power Design", "aliases": ["low power"]},
        {"canonical": "Microcontroller", "aliases": ["mcu"]},
    ],
    "testing_qa": [
        {"canonical": "PyTest", "aliases": ["pytest"]},
        {"canonical": "unittest", "aliases": []},
        {"canonical": "Jest", "aliases": []},
        {"canonical": "Mocha", "aliases": ["mocha.js"]},
        {"canonical": "Chai", "aliases": []},
        {"canonical": "Jasmine", "aliases": []},
        {"canonical": "Karma", "aliases": []},
        {"canonical": "Cypress", "aliases": []},
        {"canonical": "Playwright", "aliases": []},
        {"canonical": "Puppeteer", "aliases": []},
        {"canonical": "Selenium", "aliases": ["selenium webdriver"]},
        {"canonical": "Appium", "aliases": []},
        {"canonical": "JUnit", "aliases": ["junit5"]},
        {"canonical": "TestNG", "aliases": []},
        {"canonical": "RSpec", "aliases": []},
        {"canonical": "Cucumber", "aliases": []},
        {"canonical": "SpecFlow", "aliases": []},
        {"canonical": "PHPUnit", "aliases": []},
        {"canonical": "XCTest", "aliases": []},
        {"canonical": "Espresso", "aliases": ["android espresso"]},
        {"canonical": "Robolectric", "aliases": []},
        {"canonical": "Postman", "aliases": []},
        {"canonical": "Newman", "aliases": []},
        {"canonical": "JMeter", "aliases": ["apache jmeter"]},
        {"canonical": "LoadRunner", "aliases": ["load runner"]},
        {"canonical": "Gatling", "aliases": []},
        {"canonical": "K6", "aliases": ["k6.io"]},
        {"canonical": "Locust", "aliases": []},
        {"canonical": "TDD", "aliases": ["test driven development"]},
        {"canonical": "BDD", "aliases": ["behavior driven development"]},
        {"canonical": "Code Coverage", "aliases": ["test coverage"]},
        {"canonical": "Mocking", "aliases": ["mock objects"]},
        {"canonical": "Fixtures", "aliases": []},
        {"canonical": "Integration Testing", "aliases": []},
        {"canonical": "Unit Testing", "aliases": []},
        {"canonical": "E2E Testing", "aliases": ["end to end testing"]},
    ],
    "vcs_dev_tools": [
        {"canonical": "Git", "aliases": []},
        {"canonical": "GitHub", "aliases": []},
        {"canonical": "GitLab", "aliases": []},
        {"canonical": "Bitbucket", "aliases": []},
        {"canonical": "SVN", "aliases": ["subversion"]},
        {"canonical": "Mercurial", "aliases": ["hg"]},
        {"canonical": "Perforce", "aliases": ["p4"]},
        {"canonical": "VS Code", "aliases": ["vscode", "visual studio code"]},
        {"canonical": "IntelliJ IDEA", "aliases": ["intellij"]},
        {"canonical": "PyCharm", "aliases": []},
        {"canonical": "WebStorm", "aliases": []},
        {"canonical": "Sublime Text", "aliases": []},
        {"canonical": "Vim", "aliases": []},
        {"canonical": "Emacs", "aliases": []},
        {"canonical": "Neovim", "aliases": ["nvim"]},
        {"canonical": "Eclipse", "aliases": ["eclipse ide"]},
        {"canonical": "Xcode", "aliases": []},
        {"canonical": "Android Studio", "aliases": []},
        {"canonical": "NetBeans", "aliases": []},
        {"canonical": "RStudio", "aliases": []},
        {"canonical": "Visual Studio", "aliases": []},
        {"canonical": "Cursor", "aliases": []},
    ],
    "security": [
        {"canonical": "OAuth", "aliases": ["oauth2", "oauth 2.0"]},
        {"canonical": "OpenID Connect", "aliases": ["oidc"]},
        {"canonical": "SAML", "aliases": []},
        {"canonical": "JWT", "aliases": ["json web token"]},
        {"canonical": "TLS", "aliases": ["ssl/tls"]},
        {"canonical": "SSL", "aliases": []},
        {"canonical": "HTTPS", "aliases": []},
        {"canonical": "PKI", "aliases": ["public key infrastructure"]},
        {"canonical": "mTLS", "aliases": ["mutual tls"]},
        {"canonical": "Kerberos", "aliases": []},
        {"canonical": "LDAP", "aliases": []},
        {"canonical": "Active Directory", "aliases": ["ad"]},
        {"canonical": "SSO", "aliases": ["single sign on"]},
        {"canonical": "MFA", "aliases": ["multi factor authentication", "2fa"]},
        {"canonical": "HashiCorp Vault", "aliases": ["vault"]},
        {"canonical": "KMS", "aliases": ["key management service"]},
        {"canonical": "HSM", "aliases": ["hardware security module"]},
        {"canonical": "OWASP", "aliases": ["owasp top 10"]},
        {"canonical": "Penetration Testing", "aliases": ["pen testing", "pentest"]},
        {"canonical": "Burp Suite", "aliases": ["burpsuite"]},
        {"canonical": "Metasploit", "aliases": []},
        {"canonical": "Nmap", "aliases": []},
        {"canonical": "Wireshark", "aliases": []},
        {"canonical": "Nessus", "aliases": []},
        {"canonical": "Snyk", "aliases": []},
        {"canonical": "SAST", "aliases": ["static application security testing"]},
        {"canonical": "DAST", "aliases": ["dynamic application security testing"]},
        {"canonical": "SIEM", "aliases": []},
        {"canonical": "XDR", "aliases": []},
        {"canonical": "IAM", "aliases": ["identity and access management"]},
        {"canonical": "RBAC", "aliases": ["role based access control"]},
        {"canonical": "Zero Trust", "aliases": ["zero-trust"]},
        {"canonical": "Threat Modeling", "aliases": []},
        {"canonical": "Cryptography", "aliases": ["crypto"]},
        {"canonical": "AES", "aliases": []},
        {"canonical": "RSA", "aliases": []},
    ],
    "standards_domain": [
        {"canonical": "ISO 13485", "aliases": []},
        {"canonical": "ISO 14971", "aliases": []},
        {"canonical": "ISO 9001", "aliases": []},
        {"canonical": "ISO 27001", "aliases": []},
        {"canonical": "IEC 62304", "aliases": []},
        {"canonical": "IEC 60601", "aliases": ["60601-1"]},
        {"canonical": "IEC 61010", "aliases": []},
        {"canonical": "IEC 61508", "aliases": []},
        {"canonical": "ISO 26262", "aliases": []},
        {"canonical": "FDA 21 CFR Part 11", "aliases": ["21 cfr 11"]},
        {"canonical": "HIPAA", "aliases": []},
        {"canonical": "GDPR", "aliases": []},
        {"canonical": "CCPA", "aliases": []},
        {"canonical": "SOC 2", "aliases": ["soc2"]},
        {"canonical": "PCI DSS", "aliases": ["pci-dss"]},
        {"canonical": "GxP", "aliases": []},
        {"canonical": "GMP", "aliases": ["cgmp"]},
        {"canonical": "GLP", "aliases": []},
        {"canonical": "GCP", "aliases": ["good clinical practice"]},
        {"canonical": "FDA", "aliases": ["us fda"]},
        {"canonical": "EMA", "aliases": []},
        {"canonical": "MDR", "aliases": ["eu mdr", "medical device regulation"]},
        {"canonical": "IVDR", "aliases": []},
        {"canonical": "HL7", "aliases": []},
        {"canonical": "FHIR", "aliases": []},
        {"canonical": "DICOM", "aliases": []},
        {"canonical": "DO-178C", "aliases": ["do 178c", "do178c"]},
        {"canonical": "DO-254", "aliases": ["do 254", "do254"]},
        {"canonical": "AUTOSAR", "aliases": []},
        {"canonical": "MISRA", "aliases": ["misra c"]},
        {"canonical": "ITAR", "aliases": []},
        {"canonical": "EAR", "aliases": ["ear99"]},
        {"canonical": "CGP", "aliases": ["controlled goods program"]},
        {"canonical": "ARINC", "aliases": []},
        {"canonical": "RTCA", "aliases": []},
        {"canonical": "ANSI", "aliases": []},
        {"canonical": "ASME", "aliases": []},
        {"canonical": "ASTM", "aliases": []},
        {"canonical": "NIST", "aliases": []},
        {"canonical": "CMMC", "aliases": []},
        {"canonical": "Design Controls", "aliases": ["design control"]},
        {"canonical": "DHF", "aliases": ["design history file"]},
        {"canonical": "V&V", "aliases": ["verification and validation"]},
        {"canonical": "Risk Management", "aliases": []},
    ],
    "networking": [
        {"canonical": "TCP", "aliases": []},
        {"canonical": "IP", "aliases": ["ipv4", "ipv6"]},
        {"canonical": "UDP", "aliases": []},
        {"canonical": "DNS", "aliases": []},
        {"canonical": "DHCP", "aliases": []},
        {"canonical": "BGP", "aliases": []},
        {"canonical": "OSPF", "aliases": []},
        {"canonical": "EIGRP", "aliases": []},
        {"canonical": "VPN", "aliases": []},
        {"canonical": "IPsec", "aliases": ["ipsec vpn"]},
        {"canonical": "WireGuard", "aliases": []},
        {"canonical": "VLAN", "aliases": []},
        {"canonical": "VXLAN", "aliases": []},
        {"canonical": "SDN", "aliases": ["software defined networking"]},
        {"canonical": "MPLS", "aliases": []},
        {"canonical": "SNMP", "aliases": []},
        {"canonical": "NTP", "aliases": []},
        {"canonical": "FTP", "aliases": ["sftp"]},
        {"canonical": "SSH", "aliases": []},
        {"canonical": "gRPC", "aliases": ["grpc"]},
    ],
    "apis_protocols": [
        {"canonical": "REST", "aliases": ["restful", "rest api"]},
        {"canonical": "GraphQL", "aliases": []},
        {"canonical": "WebSocket", "aliases": ["websockets"]},
        {"canonical": "Server-Sent Events", "aliases": ["sse"]},
        {"canonical": "JSON-RPC", "aliases": []},
        {"canonical": "XML-RPC", "aliases": []},
        {"canonical": "SOAP", "aliases": []},
        {"canonical": "WebRTC", "aliases": []},
        {"canonical": "Webhooks", "aliases": ["webhook"]},
        {"canonical": "OpenAPI", "aliases": ["swagger"]},
        {"canonical": "AsyncAPI", "aliases": []},
        {"canonical": "Protocol Buffers", "aliases": ["protobuf"]},
        {"canonical": "Avro", "aliases": ["apache avro"]},
        {"canonical": "Thrift", "aliases": ["apache thrift"]},
        {"canonical": "MessagePack", "aliases": ["msgpack"]},
        {"canonical": "JSON", "aliases": []},
        {"canonical": "XML", "aliases": []},
        {"canonical": "YAML", "aliases": ["yml"]},
        {"canonical": "TOML", "aliases": []},
        {"canonical": "CSV", "aliases": []},
    ],
    "business_agile": [
        {"canonical": "Agile", "aliases": ["agile methodology"]},
        {"canonical": "Scrum", "aliases": []},
        {"canonical": "Kanban", "aliases": []},
        {"canonical": "SAFe", "aliases": ["scaled agile framework"]},
        {"canonical": "Lean", "aliases": ["lean methodology"]},
        {"canonical": "Six Sigma", "aliases": ["6 sigma"]},
        {"canonical": "Waterfall", "aliases": []},
        {"canonical": "JIRA", "aliases": ["atlassian jira"]},
        {"canonical": "Confluence", "aliases": []},
        {"canonical": "Trello", "aliases": []},
        {"canonical": "Asana", "aliases": []},
        {"canonical": "Monday.com", "aliases": ["monday"]},
        {"canonical": "Notion", "aliases": []},
        {"canonical": "ClickUp", "aliases": []},
        {"canonical": "Miro", "aliases": []},
        {"canonical": "Figma", "aliases": []},
        {"canonical": "Sketch", "aliases": ["sketch app"]},
        {"canonical": "Adobe XD", "aliases": ["adobexd"]},
        {"canonical": "InVision", "aliases": []},
        {"canonical": "Zeplin", "aliases": []},
        {"canonical": "Balsamiq", "aliases": []},
        {"canonical": "User Research", "aliases": []},
        {"canonical": "UX", "aliases": ["user experience"]},
        {"canonical": "UI", "aliases": ["user interface"]},
        {"canonical": "Wireframing", "aliases": ["wireframes"]},
        {"canonical": "Prototyping", "aliases": []},
        {"canonical": "A/B Testing", "aliases": ["a b testing", "split testing"]},
        {"canonical": "Product Roadmap", "aliases": ["roadmapping"]},
        {"canonical": "OKR", "aliases": ["objectives and key results"]},
        {"canonical": "KPI", "aliases": ["key performance indicator"]},
        {"canonical": "PRD", "aliases": ["product requirements document"]},
        {"canonical": "Stakeholder Management", "aliases": []},
    ],
    "finance_erp": [
        {"canonical": "SAP", "aliases": ["sap erp"]},
        {"canonical": "Oracle Financials", "aliases": ["oracle ebs"]},
        {"canonical": "QuickBooks", "aliases": []},
        {"canonical": "Xero", "aliases": []},
        {"canonical": "NetSuite", "aliases": ["oracle netsuite"]},
        {"canonical": "Sage", "aliases": ["sage 50", "sage 100"]},
        {"canonical": "Workday", "aliases": []},
        {"canonical": "MYOB", "aliases": []},
        {"canonical": "FreshBooks", "aliases": []},
        {"canonical": "FreeAgent", "aliases": []},
        {"canonical": "Peachtree", "aliases": []},
        {"canonical": "GAAP", "aliases": []},
        {"canonical": "IFRS", "aliases": []},
        {"canonical": "SOX", "aliases": ["sarbanes oxley"]},
        {"canonical": "Financial Modeling", "aliases": ["financial modelling"]},
        {"canonical": "Excel", "aliases": ["microsoft excel"]},
        {"canonical": "VBA", "aliases": ["excel vba"]},
        {"canonical": "DCF", "aliases": ["discounted cash flow"]},
        {"canonical": "Reconciliation", "aliases": ["account reconciliation"]},
        {"canonical": "Forecasting", "aliases": ["financial forecasting"]},
        {"canonical": "Budgeting", "aliases": []},
        {"canonical": "Audit", "aliases": ["auditing"]},
        {"canonical": "Payroll", "aliases": []},
    ],
    "tools_saas": [
        {"canonical": "Slack", "aliases": []},
        {"canonical": "Zoom", "aliases": []},
        {"canonical": "Microsoft Teams", "aliases": ["ms teams"]},
        {"canonical": "Google Workspace", "aliases": ["g suite"]},
        {"canonical": "Office 365", "aliases": ["microsoft 365", "o365"]},
        {"canonical": "SharePoint", "aliases": []},
        {"canonical": "OneDrive", "aliases": []},
        {"canonical": "Dropbox", "aliases": []},
        {"canonical": "Salesforce", "aliases": ["sfdc"]},
        {"canonical": "HubSpot", "aliases": []},
        {"canonical": "Zendesk", "aliases": []},
        {"canonical": "ServiceNow", "aliases": []},
        {"canonical": "Freshdesk", "aliases": []},
        {"canonical": "Intercom", "aliases": []},
        {"canonical": "Twilio", "aliases": []},
        {"canonical": "SendGrid", "aliases": []},
        {"canonical": "Mailchimp", "aliases": []},
        {"canonical": "Stripe", "aliases": []},
        {"canonical": "PayPal", "aliases": []},
        {"canonical": "Braintree", "aliases": []},
    ],
    # JB-51: curated multi-word skills. Whole-token matcher handles the
    # phrase form; aliases cover hyphen/space variants ("high-speed design"
    # <-> "high speed design"). Kept in one category for review clarity --
    # these are cross-cutting concepts, not owned by any single specialty.
    "multi_word_concepts": [
        # software architecture / paradigms
        {"canonical": "distributed systems", "aliases": []},
        {"canonical": "microservices architecture", "aliases": ["microservice architecture"]},
        {"canonical": "event-driven architecture", "aliases": ["event driven architecture", "eda"]},
        {"canonical": "domain-driven design", "aliases": ["domain driven design", "ddd"]},
        {"canonical": "clean architecture", "aliases": []},
        {"canonical": "systems programming", "aliases": []},
        {"canonical": "object-oriented programming", "aliases": ["object oriented programming", "oop"]},
        {"canonical": "functional programming", "aliases": []},
        # testing
        {"canonical": "test automation", "aliases": []},
        {"canonical": "performance testing", "aliases": []},
        {"canonical": "load testing", "aliases": []},
        {"canonical": "regression testing", "aliases": []},
        {"canonical": "end-to-end testing", "aliases": ["end to end testing", "e2e testing"]},
        {"canonical": "integration testing", "aliases": []},
        # data / ML core concepts
        {"canonical": "machine learning", "aliases": ["ml pipeline"]},
        {"canonical": "deep learning", "aliases": []},
        {"canonical": "reinforcement learning", "aliases": ["rl"]},
        {"canonical": "natural language processing", "aliases": ["nlp"]},
        {"canonical": "computer vision", "aliases": ["cv"]},
        {"canonical": "digital signal processing", "aliases": ["dsp"]},
        {"canonical": "signal processing", "aliases": []},
        {"canonical": "image processing", "aliases": []},
        {"canonical": "speech recognition", "aliases": []},
        {"canonical": "sensor fusion", "aliases": []},
        {"canonical": "image sensor", "aliases": []},
        {"canonical": "feature engineering", "aliases": []},
        {"canonical": "statistical modeling", "aliases": ["statistical modelling"]},
        {"canonical": "time series", "aliases": ["time-series"]},
        {"canonical": "anomaly detection", "aliases": []},
        {"canonical": "recommendation system", "aliases": ["recommender system", "recommendation engine"]},
        {"canonical": "model deployment", "aliases": []},
        {"canonical": "model monitoring", "aliases": []},
        {"canonical": "data engineering", "aliases": []},
        {"canonical": "data pipeline", "aliases": ["data pipelines"]},
        {"canonical": "data warehouse", "aliases": ["data warehousing"]},
        {"canonical": "data lake", "aliases": []},
        {"canonical": "data modeling", "aliases": ["data modelling"]},
        {"canonical": "data governance", "aliases": []},
        {"canonical": "data quality", "aliases": []},
        # hardware / embedded concepts
        {"canonical": "high-speed design", "aliases": ["high speed design"]},
        {"canonical": "power management", "aliases": []},
        {"canonical": "power electronics", "aliases": []},
        {"canonical": "embedded software", "aliases": []},
        {"canonical": "embedded systems", "aliases": []},
        {"canonical": "real-time systems", "aliases": ["real time systems"]},
        {"canonical": "model predictive control", "aliases": ["mpc"]},
        {"canonical": "control systems", "aliases": []},
        {"canonical": "root cause analysis", "aliases": ["rca"]},
        # cloud / infra concepts
        {"canonical": "fault tolerance", "aliases": ["fault tolerant"]},
        {"canonical": "high availability", "aliases": ["ha"]},
        {"canonical": "load balancing", "aliases": []},
        {"canonical": "service mesh", "aliases": []},
        {"canonical": "api gateway", "aliases": []},
        {"canonical": "event streaming", "aliases": []},
        {"canonical": "change data capture", "aliases": ["cdc"]},
        {"canonical": "continuous deployment", "aliases": []},
        # security
        {"canonical": "network security", "aliases": []},
        {"canonical": "application security", "aliases": ["appsec"]},
        {"canonical": "cloud security", "aliases": []},
        # product / design
        {"canonical": "ux research", "aliases": ["user research"]},
        {"canonical": "interaction design", "aliases": ["ixd"]},
        {"canonical": "information architecture", "aliases": ["ia"]},
        {"canonical": "design system", "aliases": ["design systems"]},
        # business / delivery
        {"canonical": "project management", "aliases": []},
        {"canonical": "program management", "aliases": []},
        {"canonical": "agile coaching", "aliases": []},
        {"canonical": "stakeholder management", "aliases": []},
        {"canonical": "product analytics", "aliases": []},
        {"canonical": "growth hacking", "aliases": []},
        {"canonical": "revenue operations", "aliases": ["revops"]},
    ],
}


# ---------- TITLES -----------------------------------------------------------
# Titles are organized similarly. For seniority variants we generate at build
# time: each stem gets Junior/Senior/Staff/Principal/Lead variants as aliases
# where the canonical form is the neutral stem. This keeps the DB compact and
# means adding one stem covers 5 seniorities.

TITLE_STEMS: dict[str, list[dict]] = {
    "software_eng": [
        {"canonical": "software engineer", "aliases": ["software developer", "swe", "sde"]},
        {"canonical": "web developer", "aliases": ["web engineer"]},
        {"canonical": "frontend engineer", "aliases": ["frontend developer", "front-end engineer", "front end developer", "ui engineer"]},
        {"canonical": "backend engineer", "aliases": ["backend developer", "back-end engineer", "back end developer", "server engineer"]},
        {"canonical": "full-stack engineer", "aliases": ["full stack engineer", "fullstack engineer", "full-stack developer", "full stack developer"]},
        {"canonical": "mobile engineer", "aliases": ["mobile developer", "mobile app developer"]},
        {"canonical": "ios engineer", "aliases": ["ios developer"]},
        {"canonical": "android engineer", "aliases": ["android developer"]},
        {"canonical": "game developer", "aliases": ["gameplay engineer", "game engineer"]},
        {"canonical": "unity developer", "aliases": []},
        {"canonical": "unreal developer", "aliases": ["unreal engine developer"]},
        {"canonical": "graphics engineer", "aliases": ["rendering engineer"]},
        {"canonical": "engine programmer", "aliases": []},
        {"canonical": "systems software engineer", "aliases": []},
        {"canonical": "kernel engineer", "aliases": ["kernel developer"]},
        {"canonical": "compiler engineer", "aliases": ["compiler developer"]},
        {"canonical": "distributed systems engineer", "aliases": []},
        {"canonical": "blockchain developer", "aliases": ["blockchain engineer"]},
        {"canonical": "smart contract developer", "aliases": []},
    ],
    "data": [
        {"canonical": "data engineer", "aliases": []},
        {"canonical": "data scientist", "aliases": []},
        {"canonical": "data analyst", "aliases": []},
        {"canonical": "analytics engineer", "aliases": []},
        {"canonical": "machine learning engineer", "aliases": ["ml engineer"]},
        {"canonical": "ai engineer", "aliases": ["artificial intelligence engineer"]},
        {"canonical": "ai researcher", "aliases": ["ai research scientist"]},
        {"canonical": "research scientist", "aliases": []},
        {"canonical": "applied scientist", "aliases": []},
        {"canonical": "computer vision engineer", "aliases": ["cv engineer"]},
        {"canonical": "nlp engineer", "aliases": ["natural language processing engineer"]},
        {"canonical": "mlops engineer", "aliases": ["ml ops engineer"]},
        {"canonical": "data platform engineer", "aliases": []},
        {"canonical": "bi developer", "aliases": ["business intelligence developer"]},
        {"canonical": "bi analyst", "aliases": ["business intelligence analyst"]},
        {"canonical": "etl developer", "aliases": []},
        {"canonical": "sql developer", "aliases": []},
        {"canonical": "report developer", "aliases": []},
        {"canonical": "data governance analyst", "aliases": []},
        {"canonical": "data steward", "aliases": []},
        {"canonical": "quantitative analyst", "aliases": ["quant"]},
        {"canonical": "quantitative researcher", "aliases": []},
    ],
    "devops_platform": [
        {"canonical": "devops engineer", "aliases": []},
        {"canonical": "site reliability engineer", "aliases": ["sre"]},
        {"canonical": "platform engineer", "aliases": []},
        {"canonical": "cloud engineer", "aliases": []},
        {"canonical": "cloud architect", "aliases": []},
        {"canonical": "infrastructure engineer", "aliases": []},
        {"canonical": "security engineer", "aliases": []},
        {"canonical": "application security engineer", "aliases": ["appsec engineer"]},
        {"canonical": "network engineer", "aliases": []},
        {"canonical": "network architect", "aliases": []},
        {"canonical": "systems administrator", "aliases": ["sysadmin", "system administrator"]},
        {"canonical": "systems engineer", "aliases": []},
        {"canonical": "database administrator", "aliases": ["dba"]},
        {"canonical": "database engineer", "aliases": []},
        {"canonical": "release engineer", "aliases": ["build engineer"]},
        {"canonical": "automation engineer", "aliases": []},
        {"canonical": "observability engineer", "aliases": []},
    ],
    "hardware": [
        {"canonical": "hardware engineer", "aliases": ["hw engineer"]},
        {"canonical": "hardware design engineer", "aliases": []},
        {"canonical": "firmware engineer", "aliases": ["firmware developer"]},
        {"canonical": "embedded engineer", "aliases": ["embedded systems engineer"]},
        {"canonical": "embedded software engineer", "aliases": []},
        {"canonical": "embedded firmware engineer", "aliases": []},
        {"canonical": "fpga engineer", "aliases": ["fpga design engineer"]},
        {"canonical": "asic engineer", "aliases": ["asic design engineer"]},
        {"canonical": "verification engineer", "aliases": ["design verification engineer", "dv engineer"]},
        {"canonical": "rtl engineer", "aliases": ["rtl design engineer"]},
        {"canonical": "analog engineer", "aliases": ["analog design engineer"]},
        {"canonical": "digital design engineer", "aliases": []},
        {"canonical": "mixed-signal engineer", "aliases": ["mixed signal engineer"]},
        {"canonical": "power electronics engineer", "aliases": []},
        {"canonical": "rf engineer", "aliases": ["rf design engineer"]},
        {"canonical": "antenna engineer", "aliases": []},
        {"canonical": "pcb designer", "aliases": ["pcb layout designer"]},
        {"canonical": "pcb engineer", "aliases": ["pcb layout engineer"]},
        {"canonical": "electrical engineer", "aliases": ["ee"]},
        {"canonical": "electronics engineer", "aliases": []},
        {"canonical": "electronics design engineer", "aliases": []},
        {"canonical": "electrical design engineer", "aliases": []},
        {"canonical": "test engineer", "aliases": []},
        {"canonical": "validation engineer", "aliases": []},
        {"canonical": "systems test engineer", "aliases": []},
        {"canonical": "field applications engineer", "aliases": ["fae"]},
        {"canonical": "applications engineer", "aliases": []},
        {"canonical": "sensor engineer", "aliases": []},
        {"canonical": "mechatronics engineer", "aliases": []},
        {"canonical": "avionics engineer", "aliases": []},
        {"canonical": "silicon engineer", "aliases": []},
        {"canonical": "physical design engineer", "aliases": []},
        {"canonical": "characterization engineer", "aliases": []},
    ],
    "qa_test": [
        {"canonical": "qa engineer", "aliases": ["quality assurance engineer"]},
        {"canonical": "qa analyst", "aliases": []},
        {"canonical": "sdet", "aliases": ["software development engineer in test"]},
        {"canonical": "test automation engineer", "aliases": []},
        {"canonical": "manual tester", "aliases": ["manual qa"]},
        {"canonical": "performance engineer", "aliases": []},
        {"canonical": "quality engineer", "aliases": []},
        {"canonical": "reliability engineer", "aliases": []},
        {"canonical": "regression tester", "aliases": []},
        {"canonical": "test lead", "aliases": []},
        {"canonical": "qa manager", "aliases": []},
    ],
    "product_pm": [
        {"canonical": "product manager", "aliases": ["pm"]},
        {"canonical": "product owner", "aliases": ["po"]},
        {"canonical": "technical product manager", "aliases": ["tpm"]},
        {"canonical": "program manager", "aliases": []},
        {"canonical": "project manager", "aliases": []},
        {"canonical": "scrum master", "aliases": []},
        {"canonical": "delivery manager", "aliases": []},
        {"canonical": "engineering manager", "aliases": ["em"]},
        {"canonical": "software engineering manager", "aliases": []},
        {"canonical": "technical lead", "aliases": ["tech lead"]},
        {"canonical": "team lead", "aliases": []},
        {"canonical": "release manager", "aliases": []},
    ],
    "design": [
        {"canonical": "ux designer", "aliases": ["user experience designer"]},
        {"canonical": "ui designer", "aliases": ["user interface designer"]},
        {"canonical": "product designer", "aliases": []},
        {"canonical": "interaction designer", "aliases": []},
        {"canonical": "visual designer", "aliases": []},
        {"canonical": "motion designer", "aliases": []},
        {"canonical": "graphic designer", "aliases": []},
        {"canonical": "illustrator", "aliases": []},
        {"canonical": "brand designer", "aliases": ["brand identity designer"]},
        {"canonical": "design researcher", "aliases": []},
        {"canonical": "ux researcher", "aliases": ["user researcher"]},
        {"canonical": "content designer", "aliases": []},
        {"canonical": "content strategist", "aliases": []},
        {"canonical": "technical writer", "aliases": ["tech writer"]},
        {"canonical": "documentation engineer", "aliases": []},
        {"canonical": "service designer", "aliases": []},
    ],
    "architect_solutions": [
        {"canonical": "solutions architect", "aliases": ["solution architect"]},
        {"canonical": "software architect", "aliases": []},
        {"canonical": "enterprise architect", "aliases": []},
        {"canonical": "security architect", "aliases": []},
        {"canonical": "data architect", "aliases": []},
        {"canonical": "solutions engineer", "aliases": ["solution engineer"]},
        {"canonical": "sales engineer", "aliases": []},
        {"canonical": "pre-sales engineer", "aliases": ["presales engineer"]},
        {"canonical": "post-sales engineer", "aliases": []},
        {"canonical": "customer success manager", "aliases": ["csm"]},
        {"canonical": "customer success engineer", "aliases": ["cse"]},
        {"canonical": "support engineer", "aliases": []},
        {"canonical": "technical support engineer", "aliases": ["tse"]},
        {"canonical": "implementation engineer", "aliases": []},
        {"canonical": "integration engineer", "aliases": []},
        {"canonical": "onboarding specialist", "aliases": []},
    ],
    "analyst_business": [
        {"canonical": "business analyst", "aliases": ["ba"]},
        {"canonical": "systems analyst", "aliases": []},
        {"canonical": "financial analyst", "aliases": []},
        {"canonical": "investment analyst", "aliases": []},
        {"canonical": "marketing analyst", "aliases": []},
        {"canonical": "operations analyst", "aliases": []},
        {"canonical": "product analyst", "aliases": []},
        {"canonical": "growth analyst", "aliases": []},
        {"canonical": "research analyst", "aliases": []},
        {"canonical": "policy analyst", "aliases": []},
        {"canonical": "risk analyst", "aliases": []},
        {"canonical": "compliance analyst", "aliases": []},
        {"canonical": "credit analyst", "aliases": []},
        {"canonical": "underwriter", "aliases": []},
    ],
    "marketing_growth": [
        {"canonical": "marketing manager", "aliases": []},
        {"canonical": "growth manager", "aliases": ["growth marketer"]},
        {"canonical": "seo specialist", "aliases": ["seo analyst"]},
        {"canonical": "content marketer", "aliases": ["content marketing manager"]},
        {"canonical": "digital marketer", "aliases": ["digital marketing manager"]},
        {"canonical": "community manager", "aliases": []},
        {"canonical": "social media manager", "aliases": []},
        {"canonical": "communications manager", "aliases": []},
        {"canonical": "brand manager", "aliases": []},
        {"canonical": "product marketing manager", "aliases": ["pmm"]},
        {"canonical": "demand generation manager", "aliases": ["demand gen"]},
        {"canonical": "email marketing specialist", "aliases": []},
        {"canonical": "performance marketing manager", "aliases": []},
    ],
    "hr_people": [
        {"canonical": "recruiter", "aliases": []},
        {"canonical": "technical recruiter", "aliases": []},
        {"canonical": "hr business partner", "aliases": ["hrbp"]},
        {"canonical": "people operations", "aliases": ["people ops"]},
        {"canonical": "talent acquisition partner", "aliases": ["ta partner"]},
        {"canonical": "hr manager", "aliases": ["human resources manager"]},
        {"canonical": "hr generalist", "aliases": []},
        {"canonical": "compensation analyst", "aliases": []},
        {"canonical": "benefits administrator", "aliases": []},
        {"canonical": "chief people officer", "aliases": ["cpo"]},
    ],
    "finance_accounting": [
        {"canonical": "accountant", "aliases": ["staff accountant"]},
        {"canonical": "senior accountant", "aliases": []},
        {"canonical": "financial controller", "aliases": ["controller"]},
        {"canonical": "chief financial officer", "aliases": ["cfo"]},
        {"canonical": "bookkeeper", "aliases": []},
        {"canonical": "auditor", "aliases": []},
        {"canonical": "internal auditor", "aliases": []},
        {"canonical": "external auditor", "aliases": []},
        {"canonical": "tax accountant", "aliases": ["tax specialist"]},
        {"canonical": "treasury analyst", "aliases": []},
        {"canonical": "fp&a analyst", "aliases": ["financial planning and analysis analyst"]},
        {"canonical": "billing specialist", "aliases": []},
        {"canonical": "collections specialist", "aliases": []},
    ],
    "healthcare_clinical": [
        {"canonical": "registered nurse", "aliases": ["rn"]},
        {"canonical": "nurse practitioner", "aliases": ["np"]},
        {"canonical": "licensed practical nurse", "aliases": ["lpn"]},
        {"canonical": "physician", "aliases": ["md", "doctor"]},
        {"canonical": "surgeon", "aliases": []},
        {"canonical": "pharmacist", "aliases": []},
        {"canonical": "radiologist", "aliases": []},
        {"canonical": "cardiologist", "aliases": []},
        {"canonical": "anesthesiologist", "aliases": []},
        {"canonical": "medical device engineer", "aliases": []},
        {"canonical": "biomedical engineer", "aliases": []},
        {"canonical": "clinical engineer", "aliases": []},
        {"canonical": "regulatory affairs specialist", "aliases": ["regulatory specialist"]},
        {"canonical": "clinical research associate", "aliases": ["cra"]},
        {"canonical": "medical writer", "aliases": []},
        {"canonical": "clinical data manager", "aliases": []},
        {"canonical": "medical laboratory technologist", "aliases": ["mlt"]},
        {"canonical": "respiratory therapist", "aliases": []},
        {"canonical": "physical therapist", "aliases": ["physiotherapist"]},
    ],
    "other_eng": [
        {"canonical": "mechanical engineer", "aliases": []},
        {"canonical": "manufacturing engineer", "aliases": []},
        {"canonical": "process engineer", "aliases": []},
        {"canonical": "industrial engineer", "aliases": []},
        {"canonical": "safety engineer", "aliases": []},
        {"canonical": "environmental engineer", "aliases": []},
        {"canonical": "civil engineer", "aliases": []},
        {"canonical": "structural engineer", "aliases": []},
        {"canonical": "chemical engineer", "aliases": []},
        {"canonical": "aerospace engineer", "aliases": []},
        {"canonical": "automotive engineer", "aliases": []},
        {"canonical": "robotics engineer", "aliases": []},
        {"canonical": "controls engineer", "aliases": []},
        {"canonical": "instrumentation engineer", "aliases": []},
        {"canonical": "materials engineer", "aliases": []},
        {"canonical": "petroleum engineer", "aliases": []},
        {"canonical": "mining engineer", "aliases": []},
        {"canonical": "nuclear engineer", "aliases": []},
        {"canonical": "geotechnical engineer", "aliases": []},
        {"canonical": "hydraulic engineer", "aliases": []},
        {"canonical": "hvac engineer", "aliases": []},
        {"canonical": "thermal engineer", "aliases": []},
        {"canonical": "structural analysis engineer", "aliases": []},
        {"canonical": "cfd engineer", "aliases": ["computational fluid dynamics engineer"]},
        {"canonical": "fea engineer", "aliases": ["finite element analysis engineer"]},
    ],
    "consultant_advisor": [
        {"canonical": "management consultant", "aliases": []},
        {"canonical": "strategy consultant", "aliases": []},
        {"canonical": "it consultant", "aliases": []},
        {"canonical": "business consultant", "aliases": []},
        {"canonical": "technology consultant", "aliases": []},
        {"canonical": "salesforce consultant", "aliases": []},
        {"canonical": "sap consultant", "aliases": []},
        {"canonical": "cybersecurity consultant", "aliases": []},
        {"canonical": "cloud consultant", "aliases": []},
        {"canonical": "digital transformation consultant", "aliases": []},
    ],
    "education_research": [
        {"canonical": "instructor", "aliases": []},
        {"canonical": "teacher", "aliases": []},
        {"canonical": "trainer", "aliases": ["corporate trainer"]},
        {"canonical": "curriculum designer", "aliases": []},
        {"canonical": "learning designer", "aliases": ["learning experience designer"]},
        {"canonical": "instructional designer", "aliases": ["id"]},
        {"canonical": "educator", "aliases": []},
        {"canonical": "professor", "aliases": []},
        {"canonical": "lecturer", "aliases": []},
        {"canonical": "adjunct professor", "aliases": []},
        {"canonical": "teaching assistant", "aliases": ["ta"]},
        {"canonical": "research assistant", "aliases": ["ra"]},
        {"canonical": "postdoctoral researcher", "aliases": ["postdoc"]},
        {"canonical": "phd student", "aliases": ["doctoral student"]},
        {"canonical": "research engineer", "aliases": []},
    ],
    "operations_ops": [
        {"canonical": "operations manager", "aliases": ["ops manager"]},
        {"canonical": "supply chain manager", "aliases": []},
        {"canonical": "logistics coordinator", "aliases": []},
        {"canonical": "warehouse manager", "aliases": []},
        {"canonical": "procurement specialist", "aliases": []},
        {"canonical": "purchasing manager", "aliases": []},
        {"canonical": "facilities manager", "aliases": []},
        {"canonical": "office manager", "aliases": []},
        {"canonical": "executive assistant", "aliases": ["ea"]},
        {"canonical": "administrative assistant", "aliases": []},
        {"canonical": "chief operating officer", "aliases": ["coo"]},
        {"canonical": "vice president of operations", "aliases": ["vp of operations"]},
    ],
    "legal": [
        {"canonical": "attorney", "aliases": ["lawyer"]},
        {"canonical": "corporate counsel", "aliases": []},
        {"canonical": "general counsel", "aliases": []},
        {"canonical": "paralegal", "aliases": []},
        {"canonical": "legal assistant", "aliases": []},
        {"canonical": "compliance officer", "aliases": []},
        {"canonical": "privacy officer", "aliases": ["dpo", "data protection officer"]},
        {"canonical": "contract manager", "aliases": []},
    ],
    "sales_bd": [
        {"canonical": "account executive", "aliases": ["ae"]},
        {"canonical": "account manager", "aliases": []},
        {"canonical": "sales development representative", "aliases": ["sdr"]},
        {"canonical": "business development representative", "aliases": ["bdr"]},
        {"canonical": "business development manager", "aliases": ["bdm"]},
        {"canonical": "sales manager", "aliases": []},
        {"canonical": "sales director", "aliases": []},
        {"canonical": "vp of sales", "aliases": ["vice president of sales"]},
        {"canonical": "chief revenue officer", "aliases": ["cro"]},
        {"canonical": "partnerships manager", "aliases": []},
        {"canonical": "channel manager", "aliases": []},
        {"canonical": "sales operations manager", "aliases": ["sales ops"]},
    ],
    "leadership_exec": [
        {"canonical": "chief executive officer", "aliases": ["ceo"]},
        {"canonical": "chief technology officer", "aliases": ["cto"]},
        {"canonical": "chief information officer", "aliases": ["cio"]},
        {"canonical": "chief information security officer", "aliases": ["ciso"]},
        {"canonical": "chief data officer", "aliases": ["cdo"]},
        {"canonical": "chief product officer", "aliases": ["cpo"]},
        {"canonical": "chief marketing officer", "aliases": ["cmo"]},
        {"canonical": "vp of engineering", "aliases": ["vice president of engineering"]},
        {"canonical": "vp of product", "aliases": []},
        {"canonical": "vp of marketing", "aliases": []},
        {"canonical": "director of engineering", "aliases": []},
        {"canonical": "director of product", "aliases": []},
        {"canonical": "director of marketing", "aliases": []},
        {"canonical": "director of operations", "aliases": []},
        {"canonical": "director of data", "aliases": []},
        {"canonical": "head of engineering", "aliases": []},
        {"canonical": "head of product", "aliases": []},
        {"canonical": "head of design", "aliases": []},
        {"canonical": "head of growth", "aliases": []},
        {"canonical": "head of data", "aliases": []},
    ],
    "trades_skilled": [
        {"canonical": "electrician", "aliases": []},
        {"canonical": "plumber", "aliases": []},
        {"canonical": "carpenter", "aliases": []},
        {"canonical": "welder", "aliases": []},
        {"canonical": "millwright", "aliases": []},
        {"canonical": "hvac technician", "aliases": []},
        {"canonical": "machinist", "aliases": ["cnc machinist"]},
        {"canonical": "electronics technician", "aliases": []},
        {"canonical": "electrical technician", "aliases": []},
        {"canonical": "mechanical technician", "aliases": []},
        {"canonical": "diesel mechanic", "aliases": []},
        {"canonical": "auto mechanic", "aliases": ["automotive mechanic"]},
        {"canonical": "heavy equipment operator", "aliases": []},
    ],
    "warehouse_logistics": [
        {"canonical": "warehouse worker", "aliases": []},
        {"canonical": "warehouse associate", "aliases": []},
        {"canonical": "forklift operator", "aliases": []},
        {"canonical": "shipping clerk", "aliases": []},
        {"canonical": "receiving clerk", "aliases": []},
        {"canonical": "inventory coordinator", "aliases": []},
        {"canonical": "materials handler", "aliases": []},
        {"canonical": "logistics coordinator", "aliases": []},
        {"canonical": "distribution manager", "aliases": []},
        {"canonical": "fleet manager", "aliases": []},
        {"canonical": "dispatcher", "aliases": []},
        {"canonical": "route planner", "aliases": []},
        {"canonical": "picker packer", "aliases": ["order picker"]},
        {"canonical": "shipping coordinator", "aliases": []},
    ],
    "software_specialized": [
        {"canonical": "salesforce developer", "aliases": ["sfdc developer"]},
        {"canonical": "salesforce administrator", "aliases": ["sfdc admin"]},
        {"canonical": "servicenow developer", "aliases": []},
        {"canonical": "sharepoint developer", "aliases": []},
        {"canonical": "sap developer", "aliases": ["sap abap developer"]},
        {"canonical": "oracle developer", "aliases": []},
        {"canonical": "workday developer", "aliases": []},
        {"canonical": "peoplesoft developer", "aliases": []},
        {"canonical": "sitecore developer", "aliases": []},
        {"canonical": "drupal developer", "aliases": []},
        {"canonical": "wordpress developer", "aliases": []},
        {"canonical": "magento developer", "aliases": []},
        {"canonical": "shopify developer", "aliases": []},
        {"canonical": "webflow developer", "aliases": []},
        {"canonical": "hubspot developer", "aliases": []},
        {"canonical": "power platform developer", "aliases": ["powerapps developer"]},
        {"canonical": "power bi developer", "aliases": []},
        {"canonical": "tableau developer", "aliases": []},
        {"canonical": "looker developer", "aliases": []},
        {"canonical": "informatica developer", "aliases": []},
        {"canonical": "talend developer", "aliases": []},
        {"canonical": "snowflake developer", "aliases": []},
        {"canonical": "databricks engineer", "aliases": []},
        {"canonical": "big data engineer", "aliases": []},
        {"canonical": "spark developer", "aliases": []},
        {"canonical": "hadoop engineer", "aliases": []},
    ],
    "software_by_lang": [
        {"canonical": "python developer", "aliases": []},
        {"canonical": "java developer", "aliases": []},
        {"canonical": "c++ developer", "aliases": ["cpp developer"]},
        {"canonical": "c# developer", "aliases": ["csharp developer"]},
        {"canonical": ".net developer", "aliases": ["dotnet developer"]},
        {"canonical": "golang developer", "aliases": ["go developer"]},
        {"canonical": "rust developer", "aliases": []},
        {"canonical": "ruby developer", "aliases": []},
        {"canonical": "php developer", "aliases": []},
        {"canonical": "javascript developer", "aliases": ["js developer"]},
        {"canonical": "typescript developer", "aliases": ["ts developer"]},
        {"canonical": "kotlin developer", "aliases": []},
        {"canonical": "swift developer", "aliases": []},
        {"canonical": "scala developer", "aliases": []},
        {"canonical": "perl developer", "aliases": []},
        {"canonical": "r developer", "aliases": []},
        {"canonical": "matlab developer", "aliases": ["matlab engineer"]},
    ],
    "software_by_framework": [
        {"canonical": "react developer", "aliases": ["reactjs developer"]},
        {"canonical": "angular developer", "aliases": []},
        {"canonical": "vue developer", "aliases": ["vue.js developer"]},
        {"canonical": "node.js developer", "aliases": ["node developer", "nodejs developer"]},
        {"canonical": "django developer", "aliases": []},
        {"canonical": "flask developer", "aliases": []},
        {"canonical": "fastapi developer", "aliases": []},
        {"canonical": "spring developer", "aliases": ["spring boot developer"]},
        {"canonical": "rails developer", "aliases": ["ruby on rails developer"]},
        {"canonical": "laravel developer", "aliases": []},
        {"canonical": "symfony developer", "aliases": []},
        {"canonical": "ember developer", "aliases": []},
        {"canonical": "next.js developer", "aliases": ["nextjs developer"]},
        {"canonical": "gatsby developer", "aliases": []},
        {"canonical": "svelte developer", "aliases": []},
        {"canonical": "flutter developer", "aliases": []},
        {"canonical": "react native developer", "aliases": []},
        {"canonical": "unity developer", "aliases": []},
        {"canonical": "unreal developer", "aliases": []},
    ],
    "customer_facing": [
        {"canonical": "customer service representative", "aliases": ["csr"]},
        {"canonical": "customer support specialist", "aliases": []},
        {"canonical": "call center agent", "aliases": []},
        {"canonical": "help desk technician", "aliases": ["helpdesk technician"]},
        {"canonical": "it support technician", "aliases": ["it support specialist"]},
        {"canonical": "desktop support technician", "aliases": []},
        {"canonical": "field service technician", "aliases": []},
        {"canonical": "service delivery manager", "aliases": []},
        {"canonical": "customer experience manager", "aliases": ["cx manager"]},
        {"canonical": "onboarding manager", "aliases": []},
        {"canonical": "renewal manager", "aliases": []},
        {"canonical": "retention specialist", "aliases": []},
    ],
    "creative_content": [
        {"canonical": "copywriter", "aliases": []},
        {"canonical": "editor", "aliases": []},
        {"canonical": "video editor", "aliases": []},
        {"canonical": "photographer", "aliases": []},
        {"canonical": "videographer", "aliases": []},
        {"canonical": "animator", "aliases": ["2d animator", "3d animator"]},
        {"canonical": "3d artist", "aliases": []},
        {"canonical": "concept artist", "aliases": []},
        {"canonical": "sound designer", "aliases": []},
        {"canonical": "audio engineer", "aliases": []},
        {"canonical": "podcast producer", "aliases": []},
        {"canonical": "content creator", "aliases": []},
        {"canonical": "youtuber", "aliases": []},
        {"canonical": "streamer", "aliases": []},
        {"canonical": "journalist", "aliases": ["reporter"]},
        {"canonical": "producer", "aliases": []},
        {"canonical": "director", "aliases": ["film director"]},
    ],
    "science_lab": [
        {"canonical": "chemist", "aliases": []},
        {"canonical": "biologist", "aliases": []},
        {"canonical": "microbiologist", "aliases": []},
        {"canonical": "biochemist", "aliases": []},
        {"canonical": "physicist", "aliases": []},
        {"canonical": "geologist", "aliases": []},
        {"canonical": "epidemiologist", "aliases": []},
        {"canonical": "statistician", "aliases": []},
        {"canonical": "actuary", "aliases": []},
        {"canonical": "lab technician", "aliases": ["laboratory technician"]},
        {"canonical": "lab manager", "aliases": ["laboratory manager"]},
        {"canonical": "research technician", "aliases": []},
        {"canonical": "bioinformatics scientist", "aliases": ["bioinformatician"]},
        {"canonical": "computational biologist", "aliases": []},
        {"canonical": "geneticist", "aliases": []},
        {"canonical": "ecologist", "aliases": []},
        {"canonical": "environmental scientist", "aliases": []},
        {"canonical": "materials scientist", "aliases": []},
    ],
    "hospitality_retail": [
        {"canonical": "chef", "aliases": ["executive chef"]},
        {"canonical": "sous chef", "aliases": []},
        {"canonical": "line cook", "aliases": []},
        {"canonical": "barista", "aliases": []},
        {"canonical": "bartender", "aliases": []},
        {"canonical": "server", "aliases": ["waiter", "waitress"]},
        {"canonical": "host", "aliases": ["hostess"]},
        {"canonical": "restaurant manager", "aliases": []},
        {"canonical": "hotel manager", "aliases": []},
        {"canonical": "concierge", "aliases": []},
        {"canonical": "housekeeper", "aliases": []},
        {"canonical": "retail associate", "aliases": ["retail sales associate"]},
        {"canonical": "store manager", "aliases": []},
        {"canonical": "cashier", "aliases": []},
        {"canonical": "visual merchandiser", "aliases": []},
        {"canonical": "buyer", "aliases": ["retail buyer"]},
    ],
    "public_safety_gov": [
        {"canonical": "police officer", "aliases": []},
        {"canonical": "firefighter", "aliases": []},
        {"canonical": "paramedic", "aliases": ["emt"]},
        {"canonical": "security guard", "aliases": []},
        {"canonical": "security analyst", "aliases": []},
        {"canonical": "cyber security analyst", "aliases": ["cybersecurity analyst"]},
        {"canonical": "soc analyst", "aliases": ["security operations center analyst"]},
        {"canonical": "incident responder", "aliases": []},
        {"canonical": "threat intelligence analyst", "aliases": []},
        {"canonical": "government affairs manager", "aliases": []},
        {"canonical": "public policy analyst", "aliases": []},
        {"canonical": "urban planner", "aliases": ["city planner"]},
    ],
    "construction_pm": [
        {"canonical": "construction manager", "aliases": []},
        {"canonical": "site supervisor", "aliases": ["site foreman"]},
        {"canonical": "estimator", "aliases": ["construction estimator"]},
        {"canonical": "quantity surveyor", "aliases": ["qs"]},
        {"canonical": "surveyor", "aliases": ["land surveyor"]},
        {"canonical": "architect", "aliases": []},
        {"canonical": "landscape architect", "aliases": []},
        {"canonical": "interior designer", "aliases": []},
        {"canonical": "building inspector", "aliases": []},
        {"canonical": "safety officer", "aliases": ["hse officer"]},
        {"canonical": "project engineer", "aliases": []},
    ],
    "manufacturing_qa": [
        {"canonical": "quality control inspector", "aliases": ["qc inspector"]},
        {"canonical": "quality assurance specialist", "aliases": ["qa specialist"]},
        {"canonical": "quality manager", "aliases": []},
        {"canonical": "production supervisor", "aliases": []},
        {"canonical": "production planner", "aliases": []},
        {"canonical": "production manager", "aliases": []},
        {"canonical": "plant manager", "aliases": []},
        {"canonical": "operations engineer", "aliases": []},
        {"canonical": "continuous improvement engineer", "aliases": []},
        {"canonical": "lean engineer", "aliases": ["lean six sigma engineer"]},
        {"canonical": "packaging engineer", "aliases": []},
        {"canonical": "supply planner", "aliases": []},
    ],
    "additional_data_ml": [
        {"canonical": "prompt engineer", "aliases": []},
        {"canonical": "llm engineer", "aliases": ["large language model engineer"]},
        {"canonical": "generative ai engineer", "aliases": ["genai engineer"]},
        {"canonical": "conversational ai engineer", "aliases": []},
        {"canonical": "chatbot developer", "aliases": []},
        {"canonical": "reinforcement learning engineer", "aliases": ["rl engineer"]},
        {"canonical": "deep learning engineer", "aliases": ["dl engineer"]},
        {"canonical": "recommender systems engineer", "aliases": []},
        {"canonical": "search engineer", "aliases": []},
        {"canonical": "ranking engineer", "aliases": []},
        {"canonical": "personalization engineer", "aliases": []},
    ],
}

SENIORITIES = ["junior", "senior", "staff", "principal", "lead", "sr", "jr"]


def _expand_title_seniorities(rows: list[dict]) -> list[dict]:
    """For each stem, keep the neutral canonical and add seniority prefixes as
    aliases. e.g. software engineer -> senior software engineer, staff software
    engineer, lead software engineer... These all fold up to the neutral form.
    """
    out = []
    for row in rows:
        canonical = row["canonical"]
        aliases = list(row.get("aliases") or [])
        extended = []
        for a in aliases:
            extended.append(a)
        for sen in SENIORITIES:
            extended.append(f"{sen} {canonical}")
            for a in aliases:
                extended.append(f"{sen} {a}")
        seen = set()
        deduped = []
        for a in extended:
            key = a.lower().strip()
            if key and key != canonical.lower() and key not in seen:
                seen.add(key)
                deduped.append(a)
        out.append({"canonical": canonical, "aliases": deduped, "category": row.get("category", "")})
    return out


def _flatten_skills(cat_map: dict[str, list[dict]]) -> list[dict]:
    out = []
    seen = set()
    for cat, rows in cat_map.items():
        for row in rows:
            canonical = row.get("canonical", "").strip()
            if not canonical or canonical.lower() in seen:
                continue
            seen.add(canonical.lower())
            aliases = [a for a in (row.get("aliases") or []) if a]
            out.append({"canonical": canonical, "aliases": aliases, "category": cat})
    return out


def _flatten_titles(cat_map: dict[str, list[dict]]) -> list[dict]:
    all_rows: list[dict] = []
    seen = set()
    for cat, rows in cat_map.items():
        for row in rows:
            canonical = row.get("canonical", "").strip()
            if not canonical or canonical.lower() in seen:
                continue
            seen.add(canonical.lower())
            all_rows.append({"canonical": canonical, "aliases": list(row.get("aliases") or []), "category": cat})
    return _expand_title_seniorities(all_rows)


def build() -> dict:
    skills = _flatten_skills(SKILLS)
    titles = _flatten_titles(TITLE_STEMS)
    return {"skills": skills, "titles": titles}


def main():
    db = build()
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        json.dump(db, f, indent=2, ensure_ascii=False)
    print(f"wrote {OUT_PATH}: {len(db['skills'])} skills, {len(db['titles'])} titles")


if __name__ == "__main__":
    main()
